#!/usr/bin/env bash
# =============================================================================
#  mac_fix_v3.sh — Deep Remediation & Remaining Warnings Script
#  Targets remaining issues AFTER mac_repair.sh (v1) + mac_fix_v2.sh runs
#  Author : Generated by Antigravity AI
#  Date   : 2026-03-09
# =============================================================================
# Usage:
#   chmod +x mac_fix_v3.sh
#   sudo ./mac_fix_v3.sh             # Apply all fixes
#   ./mac_fix_v3.sh --dry-run        # Preview only — no changes
#   ./mac_fix_v3.sh --skip-brew      # Skip slow Homebrew steps
#   ./mac_fix_v3.sh --skip-xcode     # Skip Xcode DerivedData prompt
# =============================================================================

set -u
IFS=$'\n\t'

# ── CLI flags ─────────────────────────────────────────────────────────────────
DRY_RUN=false
SKIP_BREW=false
SKIP_XCODE=false

for arg in "$@"; do
  case "$arg" in
    --dry-run)    DRY_RUN=true ;;
    --skip-brew)  SKIP_BREW=true ;;
    --skip-xcode) SKIP_XCODE=true ;;
    -h|--help)
      echo "Usage: sudo ./mac_fix_v3.sh [--dry-run] [--skip-brew] [--skip-xcode]"
      exit 0 ;;
  esac
done

# ── Paths ─────────────────────────────────────────────────────────────────────
TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
LOG_DIR="$HOME/Desktop/mac_repair_logs"
LOG_FILE="$LOG_DIR/mac_fix_v3_${TIMESTAMP}.log"
mkdir -p "$LOG_DIR"

# ── Colours ───────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'
  CYAN='\033[0;36m';  BOLD='\033[1m';  RESET='\033[0m'
  BLUE='\033[0;34m'; MAGENTA='\033[0;35m'; WHITE='\033[1;37m'
else
  RED=''; YELLOW=''; GREEN=''; CYAN=''; BOLD=''; RESET=''; BLUE=''; MAGENTA=''; WHITE=''
fi

TOTAL_FIXED=0
TOTAL_WARNINGS=0

log_raw() { echo -e "$*" | tee -a "$LOG_FILE"; }
header()  {
  local bar; bar=$(printf '═%.0s' {1..70})
  log_raw ""; log_raw "${BOLD}${CYAN}╔${bar}╗${RESET}"
  log_raw "${BOLD}${CYAN}║  🔧 $1$(printf '%*s' $((64 - ${#1})) '')║${RESET}"
  log_raw "${BOLD}${CYAN}╚${bar}╝${RESET}"
}
ok()     { log_raw "  ${GREEN}✔${RESET}  $*"; }
warn()   { log_raw "  ${YELLOW}⚠${RESET}  $*"; ((TOTAL_WARNINGS++)) || true; }
info()   { log_raw "  ${MAGENTA}ℹ${RESET}  $*"; }
skip()   { log_raw "  ${WHITE}↷${RESET}  SKIP: $*"; }
fixed()  { log_raw "  ${GREEN}⟳${RESET}  ${GREEN}FIXED:${RESET} $*"; ((TOTAL_FIXED++)) || true; }

need_sudo() {
  if [[ $EUID -ne 0 ]]; then
    warn "Root required. Re-run: sudo $0"; return 1
  fi
  return 0
}

do_fix() {
  # do_fix "description" command args…
  local desc="$1"; shift
  if $DRY_RUN; then skip "[DRY-RUN] Would run: $*"
  else
    if "$@" >> "$LOG_FILE" 2>&1; then fixed "$desc"
    else warn "Action returned non-zero: $desc"; fi
  fi
}

# =============================================================================
# TARGET 1 — XCODE DERIVED DATA (2.1GB found in v1)
# =============================================================================
fix_xcode_derived_data() {
  header "TARGET 1 · Xcode DerivedData Cleanup"
  $SKIP_XCODE && { skip "Skipped via --skip-xcode"; return; }

  local xcode_dd="$HOME/Library/Developer/Xcode/DerivedData"
  if [[ -d "$xcode_dd" ]]; then
    local sz; sz=$(du -sh "$xcode_dd" 2>/dev/null | cut -f1 || echo "?")
    info "DerivedData size: $sz"
    if $DRY_RUN; then
      skip "[DRY-RUN] Would rm -rf $xcode_dd"
    else
      rm -rf "${xcode_dd:?}" 2>/dev/null && fixed "Xcode DerivedData cleared ($sz reclaimed)" || warn "Could not fully clear DerivedData"
    fi
  else
    ok "No Xcode DerivedData directory found"
  fi

  # Also clean Xcode caches
  local xcode_cache="$HOME/Library/Caches/com.apple.dt.Xcode"
  [[ -d "$xcode_cache" ]] && do_fix "Xcode cache cleared" rm -rf "$xcode_cache"

  # Swift Package Manager caches
  local spm_cache="$HOME/Library/Caches/org.swift.swiftpm"
  [[ -d "$spm_cache" ]] && {
    local sz; sz=$(du -sh "$spm_cache" 2>/dev/null | cut -f1 || echo "?")
    info "Swift Package Manager cache: $sz"
    do_fix "SPM cache cleared ($sz)" rm -rf "$spm_cache"
  }
}

# =============================================================================
# TARGET 2 — HOMEBREW DEEP CLEANUP
# =============================================================================
fix_homebrew() {
  header "TARGET 2 · Homebrew Deep Cleanup"
  $SKIP_BREW && { skip "Skipped via --skip-brew"; return; }

  if ! command -v brew &>/dev/null; then
    ok "Homebrew not installed — skipping"
    return
  fi

  info "Running 'brew update' ..."
  if $DRY_RUN; then skip "[DRY-RUN] Would run: brew update"
  else brew update >> "$LOG_FILE" 2>&1 && fixed "Homebrew updated" || warn "brew update had issues"; fi

  info "Running 'brew upgrade' (this may take a while) ..."
  if $DRY_RUN; then skip "[DRY-RUN] Would run: brew upgrade"
  else brew upgrade >> "$LOG_FILE" 2>&1 && fixed "Homebrew packages upgraded" || warn "brew upgrade had issues (check log for details)"; fi

  info "Running 'brew cleanup --prune=all' ..."
  if $DRY_RUN; then skip "[DRY-RUN] Would run: brew cleanup --prune=all"
  else brew cleanup --prune=all >> "$LOG_FILE" 2>&1 && fixed "Homebrew cleanup done" || warn "brew cleanup had warnings (may just be nothing to clean)"; fi

  # Check for missing formulae that might cause 'brew doctor' warnings
  info "Running 'brew doctor' ..."
  local brew_issues
  brew_issues=$(brew doctor 2>&1 | grep -E 'Warning|Error' | head -10 || true)
  if [[ -n "$brew_issues" ]]; then
    warn "Homebrew doctor finds issues:"
    echo "$brew_issues" | while read -r line; do warn "  → $line"; done
  else
    ok "Homebrew doctor: all clear"
  fi
}

# =============================================================================
# TARGET 3 — /etc/hosts ANOMALY REVIEW
# =============================================================================
fix_hosts() {
  header "TARGET 3 · /etc/hosts Non-Standard Entries"
  need_sudo || return 0

  local hosts_extra
  hosts_extra=$(grep -vE '^(#|$|\s+$)' /etc/hosts 2>/dev/null \
    | grep -v '127\.0\.0\.1\|::1\|localhost\|broadcasthost\|255\.255\.255\.255' || true)

  if [[ -n "$hosts_extra" ]]; then
    warn "Non-standard entries in /etc/hosts:"
    echo "$hosts_extra" | while read -r line; do info "  $line"; done
    warn "Review and remove any entries that you did not add intentionally."
    info "Edit with: sudo nano /etc/hosts"
  else
    ok "/etc/hosts is clean (no suspicious overrides)"
  fi
}

# =============================================================================
# TARGET 4 — LAUNCHD NON-ZERO EXIT CODES
# =============================================================================
fix_launchd_exits() {
  header "TARGET 4 · LaunchD Non-Zero Exit Services"

  # List services with non-zero exit codes — these indicate crash-looping or misconfigured services
  local failed_services
  failed_services=$(launchctl list 2>/dev/null \
    | awk '$1 != "-" && $1 != "0" && $1 != "PID" && $2 != "0" {print $3 " exit(" $2 ")"}' \
    | grep -v "^com\\.apple\\." | head -20 || true)

  if [[ -n "$failed_services" ]]; then
    warn "Third-party LaunchD services with non-zero exits (potential crash loops):"
    echo "$failed_services" | while read -r svc; do
      warn "  ⟶  $svc"
    done
    info "To inspect a specific service: sudo launchctl list <service-name>"
    info "To unload: sudo launchctl bootout system/<service-name>"
  else
    ok "No third-party LaunchD crash loops found"
  fi

  # Specifically check Apple services with non-zero exits and treat as info
  local apple_exits
  apple_exits=$(launchctl list 2>/dev/null \
    | awk '$1 != "-" && $2 != "0" && $2 != "" && $3 ~ /^com\.apple\./ {print $3 " exit(" $2 ")"}' \
    | head -15 || true)

  if [[ -n "$apple_exits" ]]; then
    info "Apple system services with non-zero exits (usually transient/normal):"
    echo "$apple_exits" | while read -r svc; do info "  ⟶  $svc"; done
  fi
}

# =============================================================================
# TARGET 5 — LARGE USER CACHE PRUNING (~/Library/Caches — 12GB in v1)
# =============================================================================
fix_user_caches() {
  header "TARGET 5 · Deep User Cache Pruning (~/Library/Caches)"

  local cache_dir="$HOME/Library/Caches"
  local total_before
  total_before=$(du -sh "$cache_dir" 2>/dev/null | cut -f1 || echo "?")
  info "Total cache size before: $total_before"

  # Find the biggest cache subdirectories
  info "Top cache consumers (> 10MB):"
  find "$cache_dir" -maxdepth 1 -mindepth 1 -type d -print0 2>/dev/null \
    | xargs -0 du -sh 2>/dev/null \
    | sort -rh \
    | awk -v min=10 '
        {
          val=$1
          unit=substr(val,length(val))
          num=substr(val,1,length(val)-1)
          if (unit=="G" || (unit=="M" && num+0 >= min)) print
        }' \
    | head -20 \
    | while read -r line; do info "  $line"; done

  # Safe deep wipe — exclude active system caches to avoid UI crashes
  local SAFE_TO_DELETE=(
    "com.apple.dt.Xcode"
    "com.apple.Safari"
    "com.apple.WebKit"
    "CloudKit"
    "com.apple.bird"
    "com.apple.commerce"
    "com.apple.iTunes"
    "com.apple.Music"
    "com.apple.podcasts"
    "com.apple.appstored"
    "com.apple.nsurlsessiond"
    "com.apple.suggestd"
    "com.apple.siri.natural"
    "com.apple.photoanalysisd"
    "com.apple.mediaanalysisd"
    "com.apple.knowledgegraph"
    "pip"
    "yarn"
  )

  local freed=0
  for target in "${SAFE_TO_DELETE[@]}"; do
    local full_path="$cache_dir/$target"
    [[ -d "$full_path" ]] || continue
    local sz; sz=$(du -sh "$full_path" 2>/dev/null | cut -f1 || echo "?")
    if $DRY_RUN; then
      skip "[DRY-RUN] Would delete: $full_path ($sz)"
    else
      rm -rf "$full_path" && fixed "Cleared $target ($sz)" || warn "Could not clear $target"
    fi
    ((freed++)) || true
  done

  (( freed == 0 )) && ok "All targeted cache dirs already absent (previously cleaned)"
}

# =============================================================================
# TARGET 6 — LOGIN ITEMS & BACKGROUND TASK MGMT AUDIT
# =============================================================================
fix_login_items() {
  header "TARGET 6 · Login Items & Background Task Audit"

  # Using macOS 13+ background task management
  if command -v sfltool &>/dev/null; then
    info "System-level background tasks (via sfltool):"
    sfltool dumpbtm 2>/dev/null | head -40 | while read -r line; do info "  $line"; done || true
  fi

  # Show what's auto-starting at login via modern login items API
  if command -v pluginkit &>/dev/null; then
    info "Login items registered via PluginKit:"
    pluginkit -m -v 2>/dev/null | grep "login-item\|BackgroundTask" | head -20 \
      | while read -r line; do info "  $line"; done || true
  fi

  # Spotlight check
  info "Running Spotlight repair check..."
  local mdstatus
  mdstatus=$(mdutil -as 2>/dev/null | grep -i "error\|off" || true)
  if [[ -n "$mdstatus" ]]; then
    warn "Spotlight issues detected: $mdstatus"
    if [[ $EUID -eq 0 ]]; then
      do_fix "Spotlight re-indexed" mdutil -E /
    fi
  else
    ok "Spotlight indexing is healthy"
  fi
}

# =============================================================================
# TARGET 7 — APPLICATION SUPPORT & GROUP CONTAINERS BLOAT AUDIT
# =============================================================================
fix_app_support() {
  header "TARGET 7 · Application Support & Group Containers Audit"

  local app_support="$HOME/Library/Application Support"
  local group_containers="$HOME/Library/Group Containers"

  info "Application Support folder breakdown:"
  find "$app_support" -maxdepth 1 -mindepth 1 -type d -print0 2>/dev/null \
    | xargs -0 du -sh 2>/dev/null \
    | sort -rh \
    | head -15 \
    | while read -r line; do info "  $line"; done || true

  info "Group Containers breakdown:"
  find "$group_containers" -maxdepth 1 -mindepth 1 -type d -print0 2>/dev/null \
    | xargs -0 du -sh 2>/dev/null \
    | sort -rh \
    | head -15 \
    | while read -r line; do info "  $line"; done || true

  # Check and clean Docker data if installed
  if command -v docker &>/dev/null && [[ -d "$HOME/Library/Containers/com.docker.docker" ]]; then
    local docker_size
    docker_size=$(du -sh "$HOME/Library/Containers/com.docker.docker" 2>/dev/null | cut -f1 || echo "?")
    warn "Docker data is $docker_size — prune unused containers/images: 'docker system prune -af'"
  fi
}

# =============================================================================
# TARGET 8 — STALE / LARGE TEMPORARY FILES IN /tmp AND /var/folders
# =============================================================================
fix_temp_files() {
  header "TARGET 8 · Temporary File Wipe"
  need_sudo || return 0

  local tmp_size
  tmp_size=$(du -sh /tmp 2>/dev/null | cut -f1 || echo "?")
  info "/tmp size: $tmp_size"

  if $DRY_RUN; then
    skip "[DRY-RUN] Would run: find /tmp -mtime +3 -delete"
  else
    find /tmp -maxdepth 3 -mtime +3 -exec rm -rf {} + 2>/dev/null || true
    fixed "Cleared /tmp entries older than 3 days"
  fi

  # Apple's /var/folders user temp cache
  local var_folders_size
  var_folders_size=$(du -sh /var/folders 2>/dev/null | cut -f1 || echo "?")
  info "/var/folders size: $var_folders_size"
}

# =============================================================================
# TARGET 9 — BATTERY HEALTH SUMMARY
# =============================================================================
battery_summary() {
  header "TARGET 9 · Battery & Power Health Report"

  local batt_info cycle_count max_cap condition charge_remaining
  batt_info=$(system_profiler SPPowerDataType 2>/dev/null)
  cycle_count=$(echo "$batt_info" | awk '/Cycle Count/{print $NF}')
  max_cap=$(echo "$batt_info" | awk '/Maximum Capacity/{print $NF}')
  condition=$(echo "$batt_info" | awk '/Condition/{print $NF}')

  info "Battery Cycle Count   : ${cycle_count:-N/A}"
  info "Battery Max Capacity  : ${max_cap:-N/A}"
  info "Battery Condition     : ${condition:-N/A}"

  # Cycle count assessment
  if [[ -n "$cycle_count" ]]; then
    if (( cycle_count > 1000 )); then
      warn "High cycle count ($cycle_count) — battery replacement may be warranted (Apple threshold: ~1000)"
    elif (( cycle_count > 500 )); then
      info "Cycle count of $cycle_count — battery ageing, monitor capacity"
    else
      ok "Cycle count $cycle_count — battery is young"
    fi
  fi

  # Max capacity assessment (found 84% in v1 — flag if below 80%)
  if [[ -n "$max_cap" ]]; then
    local cap_val
    cap_val=$(echo "$max_cap" | tr -d '%')
    if (( cap_val < 80 )); then
      warn "Battery max capacity $max_cap — below 80%, Apple may consider this a replaceable battery"
    else
      ok "Battery max capacity $max_cap — within acceptable range"
    fi
  fi
}

# =============================================================================
# MAIN
# =============================================================================
main() {
  clear
  log_raw "${BOLD}${CYAN}"
  log_raw "  ╔══════════════════════════════════════════════════════════╗"
  log_raw "  ║          🔧 mac_fix_v3.sh  (Deep Remediation)           ║"
  log_raw "  ║    Targets: XCode / Homebrew / hosts / LaunchD / Cache   ║"
  log_raw "  ╚══════════════════════════════════════════════════════════╝"
  log_raw "${RESET}"

  $DRY_RUN && warn "DRY-RUN mode — no changes will be made" || true

  log_raw "  ${BOLD}Log:${RESET} $LOG_FILE"
  log_raw ""

  fix_xcode_derived_data
  fix_homebrew
  fix_hosts
  fix_launchd_exits
  fix_user_caches
  fix_login_items
  fix_app_support
  fix_temp_files
  battery_summary

  log_raw ""
  log_raw "${BOLD}${CYAN}╔══════════════════════════════════════════════════════════════════════╗${RESET}"
  log_raw "${BOLD}${CYAN}║  📋  SUMMARY                                                         ║${RESET}"
  log_raw "${BOLD}${CYAN}╚══════════════════════════════════════════════════════════════════════╝${RESET}"
  log_raw ""
  log_raw "  ${GREEN}${BOLD}🔧 Actions applied : $TOTAL_FIXED${RESET}"
  log_raw "  ${YELLOW}${BOLD}⚠️  Remaining warns : $TOTAL_WARNINGS${RESET}"
  log_raw ""
  log_raw "  ${BOLD}Full log saved to:${RESET} ${CYAN}$LOG_FILE${RESET}"
  log_raw ""
  log_raw "  Run the original diagnostic again to confirm improvement:"
  log_raw "  ${BOLD}sudo $HOME/dev/mac-repair/mac_repair.sh${RESET}"
}

main "$@"
